version: '3.1'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: sales
      MONGO_INITDB_ROOT_PASSWORD: salespwd
      MONGO_INITDB_DATABASE: sales
      TZ: "America/Maceio"
      LANG: 'cs_CS.UTF-8'
    network_mode: "host"


  salesimporter:
    image: salesimporter:1.0.0
    container_name: salesimporter
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/in:/home/in
      - ~/data/out:/home/data/out
    environment:
      TZ: "America/Maceio"
      LANG: 'cs_CS.UTF-8'
      SPRING_PROFILES_ACTIVE: prod
    network_mode: "host"

